repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.10.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-build-tools
    rev: v1.5.0
    hooks:
      - id: helm-deps
      - id: helm-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: helm/.*/templates
      - id: check-json
        exclude: helm/alfresco-keycloak/alfresco-realm.json
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
