@startuml
autonumber
Title: Alfresco JWT (Implicit) Authentication Against Keycloak Configured for LDAP

actor "User's\nBrowser" as UB
participant "App" as APP
participant "Keycloak" as KC
participant "Alfresco\nComponent\n(ACS, APS)" as ALFC
database "Alfresco\nComponent\nDatabase" as ALFCDB
participant "LDAP" as LDAP

note right of ALFC
- X endpoints represent abbreviated flows where either 
a subsystem is not configured for the scenario
or an external system does not know about the particular user
- Note that this is high-level, not all details are shown
end note

ALFC<->LDAP: LDAP User/Group Sync
ALFC<->ALFCDB
... LDAP sync completed ...
UB<->APP: Request page
UB<->APP: Login initiated
UB->KC: Request token
activate KC
note left of KC
Keycloak has not
authenticated this user
end note
KC->UB: Return login page
deactivate KC
UB->KC: Submit login form
activate KC
note left of KC
username=bsmith
password=mypass
end note
KC<->LDAP: Validate user/pass
... User is now authenticated with Keycloak ...
KC->UB: Return token
note left of KC
JWT: eyJhbGci...
end note
deactivate KC
... App / Browser has obtained JWT from Keycloak ...
UB->ALFC: GET /some-api
note right of UB
HTTP Headers
Authorization: Bearer eyJhbGci...
end note
activate ALFC
ALFC<-->KC: Get signing keys
ALFC->ALFC: Verify JWT
ALFC<->ALFCDB: User in Context
ALFC<->ALFC: Authorization/ACLs
ALFC->UB: Response
deactivate ALFC

@enduml
