{{- if contains "alfresco-realm.json" .Values.keycloakx.extraEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
type: Opaque
data:
  "alfresco-realm.json": {{ tpl (.Files.Get "alfresco-realm.json") . | b64enc | quote }}
{{- end }}
