{{- if contains "alfresco-realm.json" .Values.keycloak.keycloak.extraArgs }}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
type: Opaque
data:
  "alfresco-realm.json": {{ .Files.Get "alfresco-realm.json" | replace "ALFRESCO_CLIENT_REDIRECT_URIS" .Values.client.alfresco.redirectUris | b64enc | quote }}
{{- end }}