apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-delete-pvc-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    resourceNames: ["backup-{{ template "alfresco-identity.fullname" . }}"]
    verbs: ["delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-keycloak-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-delete-pvc-role
subjects:
  - kind: ServiceAccount
    name: {{ include "keycloak.fullname" . }}
    namespace: {{ .Release.Namespace }}
