apiVersion: batch/v1
kind: Job
metadata:
  name: up-cleanup-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "-1" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-cleanup-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-cleanup
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl delete --ignore-not-found sts {{ template "keycloak.fullname" . }} --cascade=false && kubectl delete --ignore-not-found secret realm-secret 

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "0" #Determines the order if multiple hooks are deffined    
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.postgresql.persistence.size | quote }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: up-backup-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "1" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-backup-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-backup
          image: "postgres:10.1"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }}
                  key: postgres-password
          command:
            - bash
            - -c
            - |
              pg_dump --clean --no-owner --no-acl -h {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }} \
              -p {{ .Values.keycloak.postgresql.service.port }} \
              -U {{ .Values.keycloak.keycloak.persistence.dbUser }} {{ .Values.keycloak.keycloak.persistence.dbName }} | grep -v -E '(DROP\ SCHEMA\ public|CREATE\ SCHEMA\ public|COMMENT\ ON\ SCHEMA\ public|DROP\ EXTENSION\ plpgsql|CREATE\ EXTENSION\ IF\ NOT\ EXISTS\ plpgsql|COMMENT\ ON\ EXTENSION\ plpgsql)' > /backup/backup.sql
          volumeMounts:
          - name: data
            mountPath: "/backup"
            subPath: "{{ .Values.keycloak.postgresql.persistence.subPath }}-backup"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backup-{{ template "alfresco-identity.fullname" . }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: up-dbcleanup-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "2" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-dbcleanup-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-dbcleanup
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl delete --ingnore-not-found deployment {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }}
              sleep 3

---

apiVersion: batch/v1
kind: Job
metadata:
  name: up-stopkc-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "1" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-stopkc-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-stopkc
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl scale --replicas=0 statefulset/{{ template "keycloak.fullname" . }}
              kubectl delete --ignore-not-found pod {{ template "keycloak.fullname" . }}-0

---

apiVersion: batch/v1
kind: Job
metadata:
  name: up-restore-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "2" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-restore-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-restore
          image: "postgres:11.1"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }}
                  key: postgresql-password
          command:
            - bash
            - -c
            - |
              psql -h {{ .Release.Name }}-{{ .Values.keycloak.postgresql.nameOverride }} \
              -p {{ .Values.keycloak.postgresql.service.port }} \
              -d keycloak \
              -U {{ .Values.keycloak.keycloak.persistence.dbUser }} -f /backup/backup.sql
          volumeMounts:
          - name: data
            mountPath: "/backup"
            subPath: "{{ .Values.keycloak.postgresql.persistence.subPath }}-backup"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backup-{{ template "alfresco-identity.fullname" . }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: up-startkc-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade #Determines time of deploy
    "helm.sh/hook-weight": "3" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: up-startkc-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: up-startkc
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl scale --replicas=1 statefulset/{{ template "keycloak.fullname" . }}
              sleep 3
              kubectl delete --ignore-not-found pod {{ template "keycloak.fullname" . }}-0

---

apiVersion: batch/v1
kind: Job
metadata:
  name: vol-clean-{{ template "alfresco-identity.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete #Determines time of deploy
    "helm.sh/hook-weight": "1" #Determines the order if multiple hooks are deffined
    "helm.sh/hook-delete-policy": hook-succeeded #Determines when is the object deleted
spec:
  template:
    metadata:
      name: vol-clean-{{ template "alfresco-identity.fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: vol-clean
          image: "{{ .Values.hyperkube.image.repository }}:{{ .Values.hyperkube.image.tag }}"
          imagePullPolicy: "{{ .Values.hyperkube.image.pullPolicy }}"
          command:
            - bash
            - -c
            - |
              kubectl delete --ignore-not-found pvc backup-{{ template "alfresco-identity.fullname" . }}