apiVersion: v2
name: alfresco-keycloak
version: 1.0.0
appVersion: 26.0.7
description: This is just a sample Helm installation of raw Keycloak with the Alfresco Realm and Theme pre-installed.
keywords:
  - alfresco
  - keycloak
home: https://github.com/Alfresco/alfresco-identity-service/tree/master/helm/alfresco-keycloak
sources:
  - https://github.com/Alfresco/alfresco-identity-service
maintainers:
  - name: Alfresco
dependencies:
  - name: keycloakx
    version: 2.6.0
    repository: https://codecentric.github.io/helm-charts
  - name: common
    version: 1.11.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
