{{- if .Values.ingress.enabled }}
{{- $serviceName :=  printf "%s-%s" (include "keycloak.fullname" .) "http" -}}
{{- $servicePort := .Values.keycloakx.service.httpPort -}}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "alfresco-identity.fullname" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostName }}
  - host: {{ tpl .Values.ingress.hostName . }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: {{ .Values.ingress.path }}
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ .Values.ingress.pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" $serviceName "servicePort" $servicePort "context" $) | nindent 10 }}
{{- end }}
