name: Alfresco Identity Service CI

on:
  push:
    branches:
      - master
      - AUTH-**
      - OPSEXP-**
      - feature/ACS-4606_migrate-to-GHA # TODO: remove after testing is completed
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3"

env:
  S3_ARTIFACTS_BUCKET: ${{ secrets.S3_ARTIFACTS_BUCKET }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  HELM_REPO_BASE_URL: https://kubernetes-charts.alfresco.com
  HELM_REPO: incubator
  HELM_DOCS_VERSION: 1.11.0
  AWS_REGION: eu-west-1

jobs:
  pre-commit:
    name: "Pre-commit"
    runs-on: ubuntu-latest
    continue-on-error: true # error matches Travis one, ignoring it for now
    steps:
      - name: "Install helm-docs"
        run: |
          curl -fsSL https://github.com/norwoodj/helm-docs/releases/download/v$HELM_DOCS_VERSION/helm-docs_${HELM_DOCS_VERSION}_$(uname)_x86_64.tar.gz | sudo tar xz -C /usr/local/bin/ helm-docs
          helm-docs --version
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.34.2

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_PIPELINE_AMPS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_S3_PIPELINE_AMPS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Build"
        run: |
          source distribution/build.properties
          export IDENTITY_VERSION=${IDENTITY_VERSION}        
          echo "IDENTITY_VERSION=${IDENTITY_VERSION}"
          # build and package
          cd distribution
          make || { echo "Command failed with error code $?"; sleep 1; exit 1; }
          # upload ZIP file to S3 bucket
          aws s3 cp alfresco-identity-service-${IDENTITY_VERSION}.md5 s3://${S3_ARTIFACTS_BUCKET}/ci-${BUILD_NUMBER}/
          aws s3 cp alfresco-identity-service-${IDENTITY_VERSION}.zip s3://${S3_ARTIFACTS_BUCKET}/ci-${BUILD_NUMBER}/

  test_linux:
    name: "Test (Linux)"
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_PIPELINE_AMPS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_S3_PIPELINE_AMPS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Test"
        run: |
          source distribution/build.properties
          export IDENTITY_VERSION=${IDENTITY_VERSION}        
          echo "IDENTITY_VERSION=${IDENTITY_VERSION}"
          aws s3 cp s3://${S3_ARTIFACTS_BUCKET}/ci-${BUILD_NUMBER}/alfresco-identity-service-${IDENTITY_VERSION}.zip .
          ./distribution/tests/endpoints.sh

  test_windows:
    name: "Test (Windows)"
    runs-on: windows-latest
    needs: build
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_PIPELINE_AMPS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_S3_PIPELINE_AMPS_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Get BUILD_NUMBER"
        run: |
          echo "BUILD_NUMBER=$env:GITHUB_RUN_NUMBER" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo $env:GITHUB_RUN_NUMBER
      - name: "Test"
        run: |
          $Props = convertfrom-stringdata (get-content ./distribution/build.properties -raw)
          $env:IDENTITY_VERSION = $Props.'IDENTITY_VERSION'
          echo "IDENTITY_VERSION=$env:IDENTITY_VERSION"
          aws s3 ls s3://$env:S3_ARTIFACTS_BUCKET/ci-$env:BUILD_NUMBER/
          aws s3 cp s3://$env:S3_ARTIFACTS_BUCKET/ci-$env:BUILD_NUMBER/alfresco-identity-service-$env:IDENTITY_VERSION.zip .
          unzip alfresco-identity-service-$env:IDENTITY_VERSION.zip
          cd alfresco-identity-service-$env:IDENTITY_VERSION/bin
          pwd
          dir
          echo "----- $env:GITHUB_WORKSPACE ------"
          dir $env:GITHUB_WORKSPACE
          echo "----- $env:GITHUB_WORKSPACE ------"
          powershell -Command Get-ExecutionPolicy
          powershell -Command 'Set-ExecutionPolicy unrestricted'
          powershell -Command $env:GITHUB_WORKSPACE/distribution/tests/endpoints_ps.ps1
          powershell -Command $env:GITHUB_WORKSPACE/distribution/tests/endpoints_bat.ps1
